import type { PaginationParams } from "@/shared/types/api.types";

export interface StartConversationDto {
  participantId: string;
}

export interface ConversationParticipant {
  id: string;
  name: string;
  email: string;
}

export interface Conversation {
  id: string;
  participants: ConversationParticipant[];
  lastMessage: Message | null;
  lastMessageAt: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateMessageDto {
  conversationId: string;
  content: string;
  clientId: string; // generated by client, echoed back in server replica
}

export interface DeleteMessageDto {
  messageId: string;
  conversationId: string;
}

export interface GetMessagesParams extends PaginationParams {
  conversationId: string;
  before?:string;
}

export interface Message {
  clientId: string;
  id: string;
  conversationId: string;
  sender: string;
  content: string;
  seenAt: Date | null;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;

  _status?: "PENDING" | "SENT" | "FAILED";
}

export interface MarkSeenDto {
  conversationId: string;
  seenBy: string;
}
